name: 'ExpDrop'
version: '${projectVersion}'
description: 'Drops all experience points or converts it to bottles o'' enchanting'
website: 'https://www.spigotmc.org/resources/expdrop.112907/'
author: 'CyntrixAlgorithm'
api-version: 1.17
main: 'com.github.devcyntrix.expdrop.ExpDropPlugin'
commands:
  expdrop:
    description: 'Admin command for the ExpDrop plugin'
    permission: 'expdrop.admin'
    aliases:
      - ed

permissions:
  expdrop.update:
    description: 'Notifies the player about the plugin updates'
    default: op